# M1.C4: Assignment: Python Coding \#1
Wyatt Blair

9/17/24

___

## Assignment

This assignment is designed to have you apply the concepts discussed in this module. If you have questions about the assignment, consider posting your question on the discussion board or reach out to the instructor. 

Write a Python program that will read a NxN matrix A and an NxN matrix B from an input file and outputs the NxN matrix product to C. N can be of any size >= 2. The output should display on the terminal screen.

Download the input file “A1data.txt Download A1data.txt” and place it within the current directory. 

The first line in the file is the number of rows and columns for matrix A. Depending on these values, the data will follow. Once matrix A is populated, the number of rows and columns for matrix B follow along with the data to populate matrix B.

An example of input file ‘A1data.txt’:

 
```bash
2 3
1 2 3
4 5 6
3 2
1 2
3 4
5 6
```
 

This indicates that matrix A is 2 rows and 3 columns and would be populated with the next 2 rows:  

Matrix A:

CS584_M1.C4_MatrixA.png

The next row indicates matrix B is 3 rows and 2 columns and would be populated with the next 3 rows:

Matrix B:

CS584_M1.C4_MatrixB.png

Matrix C would be the product of matrix A and matrix B:

Matrix C:

CS584_M1.C4_MatrixC.png

In your submission, you must:

Place your name and a short description of what the program is doing as comments on the first lines in the source code.
Submit (upload) your .py file (or ipynb file) on or before the due date and time.
Be sure the output is easy and clear to read.
Comment throughout the source file(s).
NOTE:

You may resubmit as many times as needed prior to the due date. 
The assignment will not be graded by your instructor until after the due date.

___

## Description

My plan here is to first write a function which does not use NumPy and which instead uses my own understanding of matrix multiplication to perform the multiplication. Then I will write a separate function which takes the same input but which uses NumPy under the hood. That way I can compare later on and see if my homebrewed function works the same as the NumPy function. Then I will write a function which reads the matrix in from the data file `A1data.txt`. Combining all of these functions which show that the homebreweed function is working.

In [1]:
import os
from typing import Literal
import numpy as np
from pprint import pprint

In [2]:
# homebrew solution
def matrix_multiplication_without_numpy(A: np.ndarray, B: np.ndarray) -> np.ndarray:

    # check that the shape makes sense
    if A.shape[1] != B.shape[0]:
        raise ValueError("Cannot multiply matrices of shape {} and {}".format(A.shape, B.shape))
    
    # create a blank version of the output matrix
    C = np.zeros((A.shape[0], B.shape[1]))

    # iterate over the rows of A
    for i in range(A.shape[0]):

        # iterate over the columns of B
        for j in range(B.shape[1]):

            # iterate over the columns of A
            for k in range(A.shape[1]):

                C[i, j] += A[i, k] * B[k, j]
    
    return C

# numpy solution for sanity check
def matrix_multiplication_with_numpy(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    return A @ B

In [3]:
# sanity check with my own test matrices and provided test matrices later on
def sanity_check(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    
    print('A @ B = C\n- - -')
    print('A:', A, '\n')
    print('B:', B, '\n - - -')

    C_wo = matrix_multiplication_without_numpy(A, B)
    C_w = matrix_multiplication_with_numpy(A, B)

    print('Without NumPy: ')
    print('C:', C_wo, '\n')
    print('With NumPy:')
    print('C:', C_w, '\n')
    print('The same?:')
    print(np.allclose(C_wo, C_w))

# make two random matrices
M, N, P = np.random.randint(2, 8), np.random.randint(2, 8), np.random.randint(2, 8)
A = np.random.rand(M, N)
B = np.random.rand(N, P)

sanity_check(A, B)

A @ B = C
- - -
A: [[0.34240275 0.12708762 0.17517395 0.29725269 0.09764981 0.94783783
  0.43921348]
 [0.35374825 0.96552578 0.26449338 0.21451254 0.81951775 0.4941837
  0.7207057 ]] 

B: [[0.89770828 0.70779331 0.42238211 0.14386039 0.26511473 0.33221975]
 [0.85468992 0.79821247 0.57421737 0.24698207 0.07050501 0.2543112 ]
 [0.33231005 0.85816645 0.17224509 0.39448823 0.01203992 0.57939161]
 [0.84093868 0.61864506 0.36540863 0.04552193 0.58646469 0.72559104]
 [0.25557175 0.57705659 0.17608585 0.03231303 0.5480696  0.6422195 ]
 [0.09018275 0.42007959 0.04084345 0.71378616 0.14245136 0.39657018]
 [0.01739614 0.90775308 0.44932095 0.0628684  0.82998204 0.31659822]] 
 - - -
Without NumPy: 
C: [[0.84225741 1.5312298  0.6096478  0.87060367 0.82925259 1.040902  ]
 [1.67762351 2.71548926 1.31609884 0.82799467 1.40856948 1.62242274]] 

With NumPy:
C: [[0.84225741 1.5312298  0.6096478  0.87060367 0.82925259 1.040902  ]
 [1.67762351 2.71548926 1.31609884 0.82799467 1.40856948 1.62242274]] 

The 

In [4]:
# write a function to read the matrix file
def read_matrix_file(file_path: str) -> dict[Literal['A', 'B'], np.ndarray]:
    
    # load the text file into a list of strings
    with open(file_path, 'r') as f:
        lines = f.readlines()
    
    # get the size of the A matrix
    num_rows_A, num_cols_A = map(int, lines[0].split(' '))

    # build the A matrix (skip the line which contains the size)
    data_A = lines[1:1+int(num_rows_A)]
    A = np.array([
        list(map(int, row.split(' ')))
        for row in data_A
    ])

    # build the B matrix
    starting_ind = num_rows_A + 1
    data_B = lines[starting_ind+1:]
    B = np.array([
        list(map(int, row.split(' ')))
        for row in data_B
    ])

    return {
        'A': A,
        'B': B,
    }

In [5]:
fp = '../data/A1data.txt'
matrices = read_matrix_file(fp)

In [6]:
matrices

{'A': array([[1, 2, 3],
        [4, 5, 6]]),
 'B': array([[1, 2],
        [3, 4],
        [5, 6]])}

In [7]:
sanity_check(**matrices)

A @ B = C
- - -
A: [[1 2 3]
 [4 5 6]] 

B: [[1 2]
 [3 4]
 [5 6]] 
 - - -
Without NumPy: 
C: [[22. 28.]
 [49. 64.]] 

With NumPy:
C: [[22 28]
 [49 64]] 

The same?:
True
